version: '3'

services:

  db:
    container_name: db
    image: mysql
    networks:
      - app-network
    environment:
      MYSQL_DATABASE: 'project'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

#  app:
#    container_name: app
#    image: awbd
#    restart: always
#    networks:
#      - app-network
#    ports:
#      - '8181:8080'
#    links:
#      - db
#    depends_on:
#      - db

networks:
  app-network:

